### ISSUE TITLE
v2.1.5 no longer works with node 0.10

### ISSUE THREAD

**Issue by mattboehm** [ben-eb/postcss-svgo#47]
postcss-svgo requires svgo v0.7. This uses ES2015 syntax, which makes it incompatible with node 0.10.

It surprises me that a patch update to postcss-svgo and minor update to svgo would drop support for node 0.10.

Anyway, I solved my issue by pinning the version of postcss-svgo, but just wanted to bring this to your attention.

Thanks!

**Comment by ben-eb** [comment]
Oh, sorry. Didn't realise there was anyone else still using this version (end-of-life next month!), have stopped running tests on 0.10 for a few months now so any support has been a happy coincidence. But officially I've stopped supporting this platform, for numerous reasons (0.12 runs the test suites much faster, among others).

Thanks for the issue! You should definitely look into upgrading to at least version 4, as 0.12 will be on its way out at the beginning of next year. 😄

**Comment by mattboehm** [comment]
Yep, I don't use it locally, but one of our customer's servers is a CentOS box and apparently that's the version they got through yum.

**Comment by mattboehm** [comment]
It'd be nice if you could specify which versions of Node you support in your package.json as described here: https://docs.npmjs.com/files/package.json#engines . I'm not sure exactly what the effect of that would be, but it may help others catch this error sooner.

**Comment by ben-eb** [comment]
Sure, would be happy to accept pull requests for any of my packages that are missing this (which is probably a majority of them). 😄

**Comment by mattboehm** [comment]
After further research, the engines are only enforced if engine-strict is set to true in the npm configs, and after a half hour of fiddling, I haven't been able to successfully make npm reject a build due to this. It's probably not worth the trouble to change this now since so few people will be using v0.10.0 and have engine-strict already set to true.

**Comment by ben-eb** [comment]
Okay, no problem. I'll make a mental note to add this in once I drop support for 0.12 (beginning next year). 👍
