### ISSUE TITLE
request support: remove charset in data url options

### ISSUE THREAD

**Issue by LiaoSept** [ben-eb/postcss-svgo#7]

**Comment by TrySound** [comment]
@LiaoSept Do you have any justification for this request?

**Comment by LiaoSept** [comment]
Because the data url charset statement is meaningless
css charset will be affected or bom ofcharset

**Comment by TrySound** [comment]
@LiaoSept Article or spec to prove it?

**Comment by ben-eb** [comment]
http://stackoverflow.com/a/32871853 says that it is a requirement.
